name: CVST Image Builder

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest Trivy version
        id: trivy-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r .tag_name)
          echo "TRIVY_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "VERSION_TAG=$(date +%Y%m%d)-${LATEST_VERSION}" >> $GITHUB_ENV

      - name: Cache last Trivy version
        id: cache-trivy
        uses: actions/cache@v3
        with:
          path: .trivy-version
          key: trivy-version-${{ env.TRIVY_VERSION }}

      - name: Check if Trivy version or code changed
        id: check-changes
        run: |
          if [ -f .trivy-version ]; then
            PREVIOUS_VERSION=$(cat .trivy-version)
            if [ "$PREVIOUS_VERSION" = "${{ env.TRIVY_VERSION }}" ] && [ "${{ github.event_name }}" != "push" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
              echo "No new Trivy version or code changes. Skipping build."
              echo "skip_build=true" >> $GITHUB_ENV
            else
              echo "${{ env.TRIVY_VERSION }}" > .trivy-version
            fi
          else
            echo "${{ env.TRIVY_VERSION }}" > .trivy-version
          fi

      - name: Set up QEMU
        if: env.skip_build != 'true'
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        if: env.skip_build != 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: env.skip_build != 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: env.skip_build != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            TRIVY_VERSION=${{ env.TRIVY_VERSION }}
          tags: |
            aomran102/cvst:${{ env.VERSION_TAG }}
            aomran102/cvst:latest