name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get latest Trivy version
        id: trivy-version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/aquasecurity/trivy/releases/latest | jq -r .tag_name)
          echo "TRIVY_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
          echo "VERSION_TAG=$(date +%Y%m%d)-${LATEST_VERSION}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            TRIVY_VERSION=${{ env.TRIVY_VERSION }}
          tags: |
            aomran102/cvst:latest
            aomran102/cvst:${{ env.VERSION_TAG }}